name = "fcVARPRO"
uuid = "501f13e3-1803-4cf0-b3d9-632f20ef7dd8"
authors = ["Carl Ganter <cganter@tum.de>"]
version = "0.1.0"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
